version: '3.8'

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3001
      - BLOG_SERVICE_URL=http://blog-service:3002
      - COMMENT_SERVICE_URL=http://comment-service:3003
      - PROFILE_SERVICE_URL=http://profile-service:3004
    depends_on:
      - auth-service
      - blog-service
      - comment-service
      - profile-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/auth
    depends_on:
      - mongodb

  blog-service:
    build: ./services/blog-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/blog
    depends_on:
      - mongodb

  comment-service:
    build: ./services/comment-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/comment
    depends_on:
      - mongodb

  profile-service:
    build: ./services/profile-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - MONGODB_URI=mongodb://mongodb:27017/profile
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 