name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install API Gateway dependencies
        working-directory: ./services/api-gateway
        run: npm ci

      - name: Run API Gateway tests
        working-directory: ./services/api-gateway
        run: npm test

      - name: Install Auth Service dependencies
        working-directory: ./services/auth-service
        run: npm ci

      - name: Run Auth Service tests
        working-directory: ./services/auth-service
        run: npm test

      - name: Install Blog Service dependencies
        working-directory: ./services/blog-service
        run: npm ci

      - name: Run Blog Service tests
        working-directory: ./services/blog-service
        run: npm test

      - name: Install Comment Service dependencies
        working-directory: ./services/comment-service
        run: npm ci

      - name: Run Comment Service tests
        working-directory: ./services/comment-service
        run: npm test

      - name: Install Profile Service dependencies
        working-directory: ./services/profile-service
        run: npm ci

      - name: Run Profile Service tests
        working-directory: ./services/profile-service
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build API Gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./services/api-gateway
          push: false
          tags: api-gateway:latest

      - name: Build Auth Service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth-service
          push: false
          tags: auth-service:latest

      - name: Build Blog Service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/blog-service
          push: false
          tags: blog-service:latest

      - name: Build Comment Service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/comment-service
          push: false
          tags: comment-service:latest

      - name: Build Profile Service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/profile-service
          push: false
          tags: profile-service:latest
